/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Java\\Code\\Blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-6658cc04",
    path: "/archives/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6658cc04").then(next)
    },
  },
  {
    path: "/archives/index.html",
    redirect: "/archives/"
  },
  {
    path: "/@pages/archivesPage.html",
    redirect: "/archives/"
  },
  {
    name: "v-d41a74a6",
    path: "/pages/d62038/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d41a74a6").then(next)
    },
  },
  {
    path: "/pages/d62038/index.html",
    redirect: "/pages/d62038/"
  },
  {
    path: "/技术文章/00.Java/00.JavaSE/01.自定义注解.html",
    redirect: "/pages/d62038/"
  },
  {
    name: "v-a1cb17d0",
    path: "/pages/3c3d63/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a1cb17d0").then(next)
    },
  },
  {
    path: "/pages/3c3d63/index.html",
    redirect: "/pages/3c3d63/"
  },
  {
    path: "/技术文章/06.中间件/01.MQ/00.RabbitMQ 使用总结.html",
    redirect: "/pages/3c3d63/"
  },
  {
    name: "v-18f58866",
    path: "/pages/2832c0/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18f58866").then(next)
    },
  },
  {
    path: "/pages/2832c0/index.html",
    redirect: "/pages/2832c0/"
  },
  {
    path: "/技术文章/01.Spring/02.Spring解决循环依赖.html",
    redirect: "/pages/2832c0/"
  },
  {
    name: "v-4d905a15",
    path: "/pages/5bed1d/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d905a15").then(next)
    },
  },
  {
    path: "/pages/5bed1d/index.html",
    redirect: "/pages/5bed1d/"
  },
  {
    path: "/技术文章/06.中间件/03.ES/00.Elasticsearch使用总结.html",
    redirect: "/pages/5bed1d/"
  },
  {
    name: "v-11b5fc3f",
    path: "/pages/384a37/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11b5fc3f").then(next)
    },
  },
  {
    path: "/pages/384a37/index.html",
    redirect: "/pages/384a37/"
  },
  {
    path: "/技术文章/01.Spring/01.Spring启动流程.html",
    redirect: "/pages/384a37/"
  },
  {
    name: "v-0b22e434",
    path: "/pages/5a87c3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b22e434").then(next)
    },
  },
  {
    path: "/pages/5a87c3/index.html",
    redirect: "/pages/5a87c3/"
  },
  {
    path: "/技术文章/00.Java/02.集合/01.List/01.List源码.html",
    redirect: "/pages/5a87c3/"
  },
  {
    name: "v-8eece7d8",
    path: "/pages/e5bd2a/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8eece7d8").then(next)
    },
  },
  {
    path: "/pages/e5bd2a/index.html",
    redirect: "/pages/e5bd2a/"
  },
  {
    path: "/技术文章/00.Java/02.集合/02.HashMap/01.HashMap源码分析.html",
    redirect: "/pages/e5bd2a/"
  },
  {
    name: "v-21ca6fe4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21ca6fe4").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    path: "/@pages/categoriesPage.html",
    redirect: "/categories/"
  },
  {
    name: "v-b72d3f20",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b72d3f20").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]