/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Corey Blog",
  "description": "我的个人博客",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "后端博客,个人技术博客,后端,后端开发,后端框架,web后端,后端面试题,技术文档,学习,面试,源码，感悟，Java,Pythn,git,github,markdown"
      }
    ],
    [
      "meta",
      {
        "name": "baidu-site-verification",
        "content": "7F55weZDDc"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#11a8cd"
      }
    ],
    [
      "script",
      {
        "data-ad-client": "ca-pub-7828333725993554",
        "async": "async",
        "src": "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-6658cc04",
      "path": "/archives/",
      "lastUpdated": "2022/03/04, 22:41:14"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "tagline": null,
        "bannerBg": "https://cdn.jsdelivr.net/gh/Wu-Corey/image_store/202203061137666.jpg",
        "features": null
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-b72d3f20",
      "path": "/",
      "lastUpdated": "2022/04/04, 11:35:06"
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-21ca6fe4",
      "path": "/categories/",
      "lastUpdated": "2022/03/04, 22:41:14"
    },
    {
      "title": "HashMap源码分析",
      "frontmatter": {
        "title": "HashMap源码分析",
        "date": "2021-12-12T13:25:09.000Z",
        "permalink": "/pages/e5bd2a/",
        "categories": [
          "技术文章",
          "Java",
          "集合",
          "HashMap"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/00.Java/02.%E9%9B%86%E5%90%88/02.HashMap/01.HashMap%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90.html",
      "relativePath": "技术文章/00.Java/02.集合/02.HashMap/01.HashMap源码分析.md",
      "key": "v-8eece7d8",
      "path": "/pages/e5bd2a/",
      "headers": [
        {
          "level": 2,
          "title": "1. put()",
          "slug": "_1-put"
        },
        {
          "level": 3,
          "title": "注释",
          "slug": "注释"
        },
        {
          "level": 3,
          "title": "hash()",
          "slug": "hash"
        },
        {
          "level": 3,
          "title": "putVal()",
          "slug": "putval"
        },
        {
          "level": 3,
          "title": "resize()",
          "slug": "resize"
        }
      ],
      "lastUpdated": "2022/03/04, 22:41:14"
    },
    {
      "title": "ReentrantLock",
      "frontmatter": {
        "title": "ReentrantLock",
        "date": "2022-04-05T09:08:26.000Z",
        "permalink": "/pages/80038c/",
        "categories": [
          "技术文章",
          "Java",
          "JUC"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/00.Java/01.JUC/01.ReentrantLock.html",
      "relativePath": "技术文章/00.Java/01.JUC/01.ReentrantLock.md",
      "key": "v-70caefcd",
      "path": "/pages/80038c/",
      "headers": [
        {
          "level": 2,
          "title": "一、概述",
          "slug": "一、概述"
        },
        {
          "level": 3,
          "title": "利用AQS自定义锁",
          "slug": "利用aqs自定义锁"
        },
        {
          "level": 2,
          "title": "二、源码",
          "slug": "二、源码"
        },
        {
          "level": 2,
          "title": "1.简介",
          "slug": "_1-简介"
        },
        {
          "level": 2,
          "title": "2.构造方法",
          "slug": "_2-构造方法"
        },
        {
          "level": 2,
          "title": "3.非公平锁实现",
          "slug": "_3-非公平锁实现"
        },
        {
          "level": 3,
          "title": "3.1加锁",
          "slug": "_3-1加锁"
        },
        {
          "level": 3,
          "title": "3.2释放锁",
          "slug": "_3-2释放锁"
        },
        {
          "level": 2,
          "title": "4.公平锁实现",
          "slug": "_4-公平锁实现"
        }
      ]
    },
    {
      "title": "深入理解Java虚拟机读书笔记（二）",
      "frontmatter": {
        "title": "深入理解Java虚拟机读书笔记（二）",
        "date": "2022-04-24T23:04:11.000Z",
        "permalink": "/pages/d9969a/",
        "categories": [
          "技术文章",
          "Java",
          "JVM"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/00.Java/03.JVM/02.%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3Java%E8%99%9A%E6%8B%9F%E6%9C%BA%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%EF%BC%88%E4%BA%8C%EF%BC%89.html",
      "relativePath": "技术文章/00.Java/03.JVM/02.深入理解Java虚拟机读书笔记（二）.md",
      "key": "v-483e9e16",
      "path": "/pages/d9969a/",
      "headers": [
        {
          "level": 2,
          "title": "三、虚拟机执行子系统",
          "slug": "三、虚拟机执行子系统"
        },
        {
          "level": 2,
          "title": "1.类文件结构",
          "slug": "_1-类文件结构"
        },
        {
          "level": 3,
          "title": "无关的基石",
          "slug": "无关的基石"
        },
        {
          "level": 3,
          "title": "Class文件的结构",
          "slug": "class文件的结构"
        },
        {
          "level": 2,
          "title": "2.虚拟机类加载机制",
          "slug": "_2-虚拟机类加载机制"
        },
        {
          "level": 3,
          "title": "2.1 概述",
          "slug": "_2-1-概述"
        },
        {
          "level": 3,
          "title": "2.2 类加载的时机",
          "slug": "_2-2-类加载的时机"
        },
        {
          "level": 3,
          "title": "2.3 类加载的过程",
          "slug": "_2-3-类加载的过程"
        },
        {
          "level": 3,
          "title": "2.4 类加载器",
          "slug": "_2-4-类加载器"
        },
        {
          "level": 2,
          "title": "3.虚拟机字节码执行引擎",
          "slug": "_3-虚拟机字节码执行引擎"
        },
        {
          "level": 3,
          "title": "3.1 概述",
          "slug": "_3-1-概述"
        },
        {
          "level": 3,
          "title": "3.2 运行时栈帧结构",
          "slug": "_3-2-运行时栈帧结构"
        },
        {
          "level": 3,
          "title": "3.3 方法调用",
          "slug": "_3-3-方法调用"
        },
        {
          "level": 3,
          "title": "3.4 基于栈的字节码解释执行引擎",
          "slug": "_3-4-基于栈的字节码解释执行引擎"
        },
        {
          "level": 2,
          "title": "4.类加载及执行子系统的案例与实战",
          "slug": "_4-类加载及执行子系统的案例与实战"
        },
        {
          "level": 3,
          "title": "1.Tomcat：",
          "slug": "_1-tomcat"
        },
        {
          "level": 3,
          "title": "2.OSGi",
          "slug": "_2-osgi"
        },
        {
          "level": 3,
          "title": "3.字节码生成技术与动态代理的实现",
          "slug": "_3-字节码生成技术与动态代理的实现"
        },
        {
          "level": 3,
          "title": "4.Retrotranslator：",
          "slug": "_4-retrotranslator"
        }
      ]
    },
    {
      "title": "AQS",
      "frontmatter": {
        "title": "AQS",
        "date": "2022-04-04T09:52:57.000Z",
        "permalink": "/pages/0cbfce/",
        "categories": [
          "技术文章",
          "Java",
          "JUC"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/00.Java/01.JUC/00.AQS.html",
      "relativePath": "技术文章/00.Java/01.JUC/00.AQS.md",
      "key": "v-48b798f9",
      "path": "/pages/0cbfce/",
      "headers": [
        {
          "level": 2,
          "title": "一、前言",
          "slug": "一、前言"
        },
        {
          "level": 3,
          "title": "问题引入",
          "slug": "问题引入"
        },
        {
          "level": 3,
          "title": "自定义AQS解决",
          "slug": "自定义aqs解决"
        },
        {
          "level": 2,
          "title": "二、概述",
          "slug": "二、概述"
        },
        {
          "level": 2,
          "title": "三、源码",
          "slug": "三、源码"
        },
        {
          "level": 3,
          "title": "1.acquire()",
          "slug": "_1-acquire"
        },
        {
          "level": 3,
          "title": "2.release()",
          "slug": "_2-release"
        },
        {
          "level": 3,
          "title": "3.acquireShared()",
          "slug": "_3-acquireshared"
        },
        {
          "level": 3,
          "title": "4.releaseShared()",
          "slug": "_4-releaseshared"
        },
        {
          "level": 3,
          "title": "5.Node",
          "slug": "_5-node"
        },
        {
          "level": 3,
          "title": "6.ConditionObject",
          "slug": "_6-conditionobject"
        },
        {
          "level": 2,
          "title": "四、特性",
          "slug": "四、特性"
        },
        {
          "level": 3,
          "title": "1.可重入与不可重入",
          "slug": "_1-可重入与不可重入"
        },
        {
          "level": 3,
          "title": "2.忽略中断与响应中断",
          "slug": "_2-忽略中断与响应中断"
        }
      ],
      "lastUpdated": "2022/04/04, 11:35:06"
    },
    {
      "title": "Spring启动流程",
      "frontmatter": {
        "title": "Spring启动流程",
        "date": "2021-12-12T13:32:19.000Z",
        "permalink": "/pages/384a37/",
        "categories": [
          "技术文章",
          "Spring"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/01.Spring/01.Spring%E5%90%AF%E5%8A%A8%E6%B5%81%E7%A8%8B.html",
      "relativePath": "技术文章/01.Spring/01.Spring启动流程.md",
      "key": "v-11b5fc3f",
      "path": "/pages/384a37/",
      "headers": [
        {
          "level": 2,
          "title": "一、源码",
          "slug": "一、源码"
        },
        {
          "level": 3,
          "title": "核心方法reflesh()",
          "slug": "核心方法reflesh"
        },
        {
          "level": 3,
          "title": "obtainFreshBeanFactory()",
          "slug": "obtainfreshbeanfactory"
        },
        {
          "level": 3,
          "title": "finishBeanFactoryInitialization(beanFactory)",
          "slug": "finishbeanfactoryinitialization-beanfactory"
        },
        {
          "level": 3,
          "title": "preInstantiateSingletons()",
          "slug": "preinstantiatesingletons"
        },
        {
          "level": 3,
          "title": "isFactoryBean()",
          "slug": "isfactorybean"
        },
        {
          "level": 3,
          "title": "getBean()",
          "slug": "getbean"
        },
        {
          "level": 3,
          "title": "doGetBean()",
          "slug": "dogetbean"
        },
        {
          "level": 3,
          "title": "createBean()",
          "slug": "createbean"
        },
        {
          "level": 3,
          "title": "doCreateBean()",
          "slug": "docreatebean"
        },
        {
          "level": 3,
          "title": "createBeanInstance()",
          "slug": "createbeaninstance"
        },
        {
          "level": 3,
          "title": "instantiateBean()",
          "slug": "instantiatebean"
        },
        {
          "level": 3,
          "title": "instantiate()",
          "slug": "instantiate"
        },
        {
          "level": 3,
          "title": "instantiateClass()",
          "slug": "instantiateclass"
        },
        {
          "level": 3,
          "title": "initializeBean()",
          "slug": "initializebean"
        },
        {
          "level": 2,
          "title": "二、总结",
          "slug": "二、总结"
        }
      ],
      "lastUpdated": "2022/03/04, 22:41:14"
    },
    {
      "title": "Spring解决循环依赖",
      "frontmatter": {
        "title": "Spring解决循环依赖",
        "date": "2021-12-12T14:25:38.000Z",
        "permalink": "/pages/2832c0/",
        "categories": [
          "技术文章",
          "Spring"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/01.Spring/02.Spring%E8%A7%A3%E5%86%B3%E5%BE%AA%E7%8E%AF%E4%BE%9D%E8%B5%96.html",
      "relativePath": "技术文章/01.Spring/02.Spring解决循环依赖.md",
      "key": "v-18f58866",
      "path": "/pages/2832c0/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "1.什么是循环依赖",
          "slug": "_1-什么是循环依赖"
        },
        {
          "level": 2,
          "title": "2.Spring如何解决循环依赖",
          "slug": "_2-spring如何解决循环依赖"
        },
        {
          "level": 2,
          "title": "3.问题与总结",
          "slug": "_3-问题与总结"
        }
      ],
      "lastUpdated": "2022/03/04, 22:41:14"
    },
    {
      "title": "自定义注解",
      "frontmatter": {
        "title": "自定义注解",
        "date": "2021-12-12T14:27:19.000Z",
        "permalink": "/pages/d62038/",
        "categories": [
          "技术文章",
          "Java",
          "JavaSE"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/00.Java/00.JavaSE/01.%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E8%A7%A3.html",
      "relativePath": "技术文章/00.Java/00.JavaSE/01.自定义注解.md",
      "key": "v-d41a74a6",
      "path": "/pages/d62038/",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "手动实现",
          "slug": "手动实现"
        },
        {
          "level": 3,
          "title": "1. 新建一个普通Java工程",
          "slug": "_1-新建一个普通java工程"
        },
        {
          "level": 3,
          "title": "2.Autowired注解类",
          "slug": "_2-autowired注解类"
        },
        {
          "level": 3,
          "title": "3.UserController类",
          "slug": "_3-usercontroller类"
        },
        {
          "level": 3,
          "title": "4.UserService类",
          "slug": "_4-userservice类"
        },
        {
          "level": 3,
          "title": "5.利用反射实现注入",
          "slug": "_5-利用反射实现注入"
        },
        {
          "level": 2,
          "title": "结果",
          "slug": "结果"
        }
      ],
      "lastUpdated": "2022/03/04, 22:41:14"
    },
    {
      "title": "RabbitMQ 使用总结",
      "frontmatter": {
        "title": "RabbitMQ 使用总结",
        "date": "2021-12-12T14:28:45.000Z",
        "permalink": "/pages/3c3d63/",
        "categories": [
          "技术文章",
          "中间件",
          "MQ"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/06.%E4%B8%AD%E9%97%B4%E4%BB%B6/01.MQ/00.RabbitMQ%20%E4%BD%BF%E7%94%A8%E6%80%BB%E7%BB%93.html",
      "relativePath": "技术文章/06.中间件/01.MQ/00.RabbitMQ 使用总结.md",
      "key": "v-a1cb17d0",
      "path": "/pages/3c3d63/",
      "headers": [
        {
          "level": 2,
          "title": "1.WEB界面",
          "slug": "_1-web界面"
        },
        {
          "level": 3,
          "title": "无法打开WEB界面",
          "slug": "无法打开web界面"
        },
        {
          "level": 3,
          "title": "后台页面信息显示不全",
          "slug": "后台页面信息显示不全"
        }
      ],
      "lastUpdated": "2022/03/04, 22:41:14"
    },
    {
      "title": "Elasticsearch使用总结",
      "frontmatter": {
        "title": "Elasticsearch使用总结",
        "date": "2022-03-04T21:29:53.000Z",
        "permalink": "/pages/5bed1d/",
        "categories": [
          "技术文章",
          "中间件",
          "ES"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/06.%E4%B8%AD%E9%97%B4%E4%BB%B6/03.ES/00.Elasticsearch%E4%BD%BF%E7%94%A8%E6%80%BB%E7%BB%93.html",
      "relativePath": "技术文章/06.中间件/03.ES/00.Elasticsearch使用总结.md",
      "key": "v-4d905a15",
      "path": "/pages/5bed1d/",
      "headers": [
        {
          "level": 2,
          "title": "例1",
          "slug": "例1"
        },
        {
          "level": 2,
          "title": "例2",
          "slug": "例2"
        }
      ],
      "lastUpdated": "2022/03/04, 22:41:14"
    },
    {
      "title": "List源码分析",
      "frontmatter": {
        "title": "List源码分析",
        "date": "2021-12-12T14:20:08.000Z",
        "permalink": "/pages/5a87c3/",
        "categories": [
          "技术文章",
          "Java",
          "集合",
          "List"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/00.Java/02.%E9%9B%86%E5%90%88/01.List/01.List%E6%BA%90%E7%A0%81.html",
      "relativePath": "技术文章/00.Java/02.集合/01.List/01.List源码.md",
      "key": "v-0b22e434",
      "path": "/pages/5a87c3/",
      "headers": [
        {
          "level": 2,
          "title": "1.扩容机制",
          "slug": "_1-扩容机制"
        },
        {
          "level": 3,
          "title": "源码分析",
          "slug": "源码分析"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 3,
          "title": "比较",
          "slug": "比较"
        }
      ],
      "lastUpdated": "2022/03/04, 22:41:14"
    },
    {
      "title": "深入理解Java虚拟机读书笔记（一）",
      "frontmatter": {
        "title": "深入理解Java虚拟机读书笔记（一）",
        "date": "2022-03-06T11:02:05.000Z",
        "permalink": "/pages/049435/",
        "categories": [
          "技术文章",
          "Java",
          "JVM"
        ]
      },
      "regularPath": "/%E6%8A%80%E6%9C%AF%E6%96%87%E7%AB%A0/00.Java/03.JVM/00.%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3Java%E8%99%9A%E6%8B%9F%E6%9C%BA%E8%AF%BB%E4%B9%A6%E7%AC%94%E8%AE%B0%EF%BC%88%E4%B8%80%EF%BC%89.html",
      "relativePath": "技术文章/00.Java/03.JVM/00.深入理解Java虚拟机读书笔记（一）.md",
      "key": "v-022cb3d7",
      "path": "/pages/049435/",
      "headers": [
        {
          "level": 2,
          "title": "1.Java内存区域与内存溢出异常",
          "slug": "_1-java内存区域与内存溢出异常"
        },
        {
          "level": 3,
          "title": "程序计数器",
          "slug": "程序计数器"
        },
        {
          "level": 3,
          "title": "Java虚拟机栈",
          "slug": "java虚拟机栈"
        },
        {
          "level": 3,
          "title": "本地方法栈",
          "slug": "本地方法栈"
        },
        {
          "level": 3,
          "title": "堆",
          "slug": "堆"
        },
        {
          "level": 3,
          "title": "方法区",
          "slug": "方法区"
        },
        {
          "level": 3,
          "title": "直接内存",
          "slug": "直接内存"
        },
        {
          "level": 3,
          "title": "对象访问",
          "slug": "对象访问"
        },
        {
          "level": 2,
          "title": "2.垃圾收集器与内存分配策略",
          "slug": "_2-垃圾收集器与内存分配策略"
        },
        {
          "level": 3,
          "title": "如何确定对象已死，需要回收？",
          "slug": "如何确定对象已死-需要回收"
        },
        {
          "level": 3,
          "title": "垃圾收集算法",
          "slug": "垃圾收集算法"
        },
        {
          "level": 3,
          "title": "垃圾收集器",
          "slug": "垃圾收集器"
        },
        {
          "level": 3,
          "title": "内存分配与回收策略",
          "slug": "内存分配与回收策略"
        },
        {
          "level": 2,
          "title": "3.虚拟机性能监控与故障处理工具",
          "slug": "_3-虚拟机性能监控与故障处理工具"
        },
        {
          "level": 3,
          "title": "命令行工具",
          "slug": "命令行工具"
        },
        {
          "level": 3,
          "title": "可视化工具",
          "slug": "可视化工具"
        },
        {
          "level": 2,
          "title": "4.调优案例分析与实战",
          "slug": "_4-调优案例分析与实战"
        },
        {
          "level": 2,
          "title": "4.调优案例分析与实战",
          "slug": "_4-调优案例分析与实战-2"
        }
      ],
      "lastUpdated": "2022/04/04, 11:35:06"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "分类",
        "link": "/categories/"
      },
      {
        "text": "归档",
        "link": "/archives/"
      }
    ],
    "sidebarDepth": 2,
    "repo": "wu-Corey/wu-Corey.github.io",
    "searchMaxSuggestions": 10,
    "lastUpdated": "上次更新",
    "docsDir": "docs",
    "editLinks": true,
    "editLinkText": "编辑",
    "tag": false,
    "sidebar": {
      "/技术文章/": [
        {
          "title": "Java",
          "collapsable": true,
          "children": [
            {
              "title": "JavaSE",
              "collapsable": true,
              "children": [
                [
                  "00.Java/00.JavaSE/01.自定义注解.md",
                  "自定义注解",
                  "/pages/d62038/"
                ]
              ]
            },
            {
              "title": "JUC",
              "collapsable": true,
              "children": [
                [
                  "00.Java/01.JUC/00.AQS.md",
                  "AQS",
                  "/pages/0cbfce/"
                ],
                [
                  "00.Java/01.JUC/01.ReentrantLock.md",
                  "ReentrantLock",
                  "/pages/80038c/"
                ]
              ]
            },
            {
              "title": "集合",
              "collapsable": true,
              "children": [
                {
                  "title": "List",
                  "collapsable": true,
                  "children": [
                    [
                      "00.Java/02.集合/01.List/01.List源码.md",
                      "List源码分析",
                      "/pages/5a87c3/"
                    ]
                  ]
                },
                {
                  "title": "HashMap",
                  "collapsable": true,
                  "children": [
                    [
                      "00.Java/02.集合/02.HashMap/01.HashMap源码分析.md",
                      "HashMap源码分析",
                      "/pages/e5bd2a/"
                    ]
                  ]
                }
              ]
            },
            {
              "title": "JVM",
              "collapsable": true,
              "children": [
                [
                  "00.Java/03.JVM/00.深入理解Java虚拟机读书笔记（一）.md",
                  "深入理解Java虚拟机读书笔记（一）",
                  "/pages/049435/"
                ],
                [
                  "00.Java/03.JVM/02.深入理解Java虚拟机读书笔记（二）.md",
                  "深入理解Java虚拟机读书笔记（二）",
                  "/pages/d9969a/"
                ]
              ]
            }
          ]
        },
        {
          "title": "Spring",
          "collapsable": true,
          "children": [
            [
              "01.Spring/01.Spring启动流程.md",
              "Spring启动流程",
              "/pages/384a37/"
            ],
            [
              "01.Spring/02.Spring解决循环依赖.md",
              "Spring解决循环依赖",
              "/pages/2832c0/"
            ]
          ]
        },
        {
          "title": "MySQL",
          "collapsable": true,
          "children": []
        },
        {
          "title": "中间件",
          "collapsable": true,
          "children": [
            {
              "title": "MQ",
              "collapsable": true,
              "children": [
                [
                  "06.中间件/01.MQ/00.RabbitMQ 使用总结.md",
                  "RabbitMQ 使用总结",
                  "/pages/3c3d63/"
                ]
              ]
            },
            {
              "title": "Redis",
              "collapsable": true,
              "children": []
            },
            {
              "title": "ES",
              "collapsable": true,
              "children": [
                [
                  "06.中间件/03.ES/00.Elasticsearch使用总结.md",
                  "Elasticsearch使用总结",
                  "/pages/5bed1d/"
                ]
              ]
            }
          ]
        },
        {
          "title": "计算机科学",
          "collapsable": true,
          "children": []
        }
      ],
      "catalogue": {}
    },
    "author": {
      "name": "Corey",
      "link": "https://github.com/Wu-Corey"
    },
    "blogger": {
      "avatar": "img/me.jpg",
      "name": "Corey",
      "slogan": "Seven times have I despised my soul"
    },
    "social": {
      "icons": [
        {
          "iconClass": "icon-youjian",
          "title": "邮箱",
          "link": "mailto:1609495628@qq.com"
        },
        {
          "iconClass": "icon-github",
          "title": "GitHub",
          "link": "https://github.com/Wu-Corey"
        },
        {
          "iconClass": "icon-erji",
          "title": "音乐",
          "link": ""
        }
      ]
    },
    "footer": {
      "createYear": 2021,
      "copyrightInfo": "Corey | <a href=\"https://github.com/xugaoyi/vuepress-theme-vdoing/blob/master/LICENSE\" target=\"_blank\">MIT License</a>"
    }
  }
}